export const SET_LOGININFO = 'SET_LOGININFO'
export const SET_ENTRY = 'SET_ENTRY'
export const SET_ROUTERTAGS = 'SET_ROUTERTAGS'
export const CLEAR_ROUTERTAGS = 'CLEAR_ROUTERTAGS'
export const REMOVE_ROUTERTAGS = 'REMOVE_ROUTERTAGS'


